FROM golang:1.18.0

ENV VERSION v1.0.42
ENV GOCACHE /tmp

WORKDIR /go/src/github/mlabouardy/movies-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-$VERSION-linux-amd64 -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy

COPY . .

RUN go get -v 